# Generated by Django 4.2.2 on 2023-06-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
    ]
