# Generated by Django 4.2.2 on 2023-06-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='no_pictute.jpg', upload_to='users'),
        ),
    ]
