# Generated by Django 4.2.2 on 2023-06-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text='You must use a comma to separate the ingredients.', max_length=255),
        ),
    ]
