# Generated by Django 4.2.2 on 2023-06-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('br', 'Breakfast'), ('dr', 'Drink'), ('lu', 'Lunch'), ('sn', 'Snack'), ('te', 'Tea')], default='br', max_length=20),
        ),
    ]
