# Generated by Django 4.2.2 on 2023-06-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_pic_alter_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('br', 'Breakfast'), ('dr', 'Drink'), ('lu', 'Lunch'), ('sn', 'Snack'), ('te', 'Tea'), ('di', 'Dinner')], default='br', max_length=20),
        ),
    ]
