# Generated by Django 4.2.2 on 2023-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('drink', 'Drink'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('tea', 'Tea'), ('dinner', 'Dinner')], max_length=50),
        ),
    ]
