# Generated by Django 4.2.2 on 2023-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(help_text='You muust use a comma to separate the ingredients.', max_length=255)),
                ('cooking_time', models.PositiveIntegerField(help_text='In minutes')),
                ('type', models.CharField(choices=[('breakfast', 'Breakfast'), ('drink', 'Drink'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('tea', 'Tea')], default='br', max_length=20)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
