# Generated by Django 4.2.2 on 2023-08-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text='You must use a comma to separate the ingredients.', max_length=300),
        ),
    ]
